### ISSUE TITLE
Update examples -- to reflect change from Focus to Active

### ISSUE THREAD

**Issue by tparker24** [asweigart/PyGetWindow#4]
Update examples -- to reflect change from Focus to Active

**Comment by littlegreenrock** [comment]
as a very very novice coder, I could not find out why xxx.focus() was not working.  I took a shot at reading into the _pygetwindow_win.py file, and no focus() found, but there was an activate()

okay, maybe if I knew what I was doing I would find it faster, but I think that the documentation change is going to take seconds to do.  

how do I github?
