### ISSUE TITLE
Contribution for MacOS Support

### ISSUE THREAD

**Issue by ashhadahmd** [asweigart/PyGetWindow#57]
## Description
Hello there, I am willing to contribute for creating MacOS support for `pygetwindow`. All I need is a list of functions and property the author requires for making the support so that the update doesn't go against any code of conducts!

I will be using Appkit for making transforming windows and getting information about them.

**Comment by Kalmat** [comment]
Hi there! as far as I know this repo has been inactive for a while (I mean, for years).

I tried to contribute myself, especially adding Linux support, but I had no answer (I wish you have better luck). I decided to fork it and build a separate cross-platform module named PyWinCtl (if you are curious, you can check it [here](https://github.com/Kalmat/PyWinCtl). To be honest, I have done my best in the macOS part, but I'm affraid it can be definitely improved (I am not a macOS expert at all).

If you don't get any answer or, in any case, you can help improving PyWinCtl, I would really appreciate it!!

**Comment by ashhadahmd** [comment]
Sure either way I want to make the library better. I have checked your package out and its amazing how much amount of work you have put into it. I will definitely work on the MacOS support and will make a pull request.

**Comment by Kalmat** [comment]
That's GREAT!! Thank you!

Feel free to totally rebuild everything you consider. If you need help or any explanation, do not hesitate to contact me.

Please take into account that PyWinCtl relies on PyWinBox module for some features. You can find it [here](https://github.com/Kalmat/PyWinBox)

Thanks again!
